on:
    workflow_dispatch:
      
jobs:
    go-release:
      runs-on: ubuntu-latest
      steps:
        - name: Check out the repository
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: Set up Go
          uses: actions/setup-go@v5
          with:
            go-version: 1.21
        - name: Run GoReleaser
          uses: goreleaser/goreleaser-action@v6
          with:
            version: latest
            args: release --clean
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}